name: Build, Test and Deploy Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 18x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "SoftUni username - kristian8"

  execute-ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 18x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install playwright dependencies
      run: npx playwright install
    - name: Start the application
      run: node index.js &
    - name: Execute the UI tests
      run: npm run test:ui

  deploy:
    needs: execute-ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_KEY }}
          api-key: ${{ secrets.RENDER_API_KEY }}